-- NOTE: create a database name WPSDB & user. And update below query with your database connect user (db2inst1) and password (diet4coke)
CONNECT TO WPSDB USER db2inst1 USING diet4coke;
CREATE SCHEMA release AUTHORIZATION db2inst1;
COMMIT;

GRANT CONNECT, CREATETAB ON DATABASE TO GROUP WP_BASE_CONFIG_USERS;
GRANT EXECUTE ON PACKAGE NULLID.SYSSH200 TO GROUP WP_BASE_CONFIG_USERS;
GRANT ALTERIN, CREATEIN, DROPIN ON SCHEMA release TO GROUP WP_BASE_CONFIG_USERS;
GRANT USE OF TABLESPACE USERSPACE1 TO GROUP WP_BASE_CONFIG_USERS;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO GROUP WP_BASE_CONFIG_USERS;

CONNECT RESET;

CONNECT TO WPSDB USER db2inst1 USING diet4coke;
CREATE SCHEMA community AUTHORIZATION db2inst1;
COMMIT;

GRANT CONNECT, CREATETAB ON DATABASE TO GROUP WP_BASE_CONFIG_USERS;
GRANT EXECUTE ON PACKAGE NULLID.SYSSH200 TO GROUP WP_BASE_CONFIG_USERS;
GRANT ALTERIN, CREATEIN, DROPIN ON SCHEMA community TO GROUP WP_BASE_CONFIG_USERS;
GRANT USE OF TABLESPACE USERSPACE1 TO GROUP WP_BASE_CONFIG_USERS;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO GROUP WP_BASE_CONFIG_USERS;

CONNECT RESET;

CONNECT TO WPSDB USER db2inst1 USING diet4coke;
CREATE SCHEMA customization AUTHORIZATION db2inst1;
COMMIT;

GRANT CONNECT, CREATETAB ON DATABASE TO GROUP WP_BASE_CONFIG_USERS;
GRANT EXECUTE ON PACKAGE NULLID.SYSSH200 TO GROUP WP_BASE_CONFIG_USERS;
GRANT ALTERIN, CREATEIN, DROPIN ON SCHEMA customization TO GROUP WP_BASE_CONFIG_USERS;
GRANT USE OF TABLESPACE USERSPACE1 TO GROUP WP_BASE_CONFIG_USERS;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO GROUP WP_BASE_CONFIG_USERS;

CONNECT RESET;

CONNECT TO WPSDB USER db2inst1 USING diet4coke;
CREATE SCHEMA jcr AUTHORIZATION db2inst1;
COMMIT;

GRANT CONNECT, CREATETAB ON DATABASE TO GROUP WP_JCR_CONFIG_USERS;
GRANT EXECUTE ON PACKAGE NULLID.SYSSH200 TO GROUP WP_JCR_CONFIG_USERS;
GRANT ALTERIN, CREATEIN, DROPIN ON SCHEMA jcr TO GROUP WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE USERSPACE1 TO GROUP WP_JCR_CONFIG_USERS;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO GROUP WP_JCR_CONFIG_USERS;


GRANT USE OF TABLESPACE ICMLFQ32 TO GROUP WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE ICMLNF32 TO GROUP WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE ICMVFQ04 TO GROUP WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE ICMSFQ04 TO GROUP WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE CMBINV04 TO GROUP WP_JCR_CONFIG_USERS;
GRANT USE OF TABLESPACE ICMLSUSRTSPACE4 TO GROUP WP_JCR_CONFIG_USERS;

CONNECT RESET;

CONNECT TO WPSDB USER db2inst1 USING diet4coke;
CREATE SCHEMA feedback AUTHORIZATION db2inst1;
COMMIT;

GRANT CONNECT, CREATETAB ON DATABASE TO GROUP WP_PZN_CONFIG_USERS;
GRANT EXECUTE ON PACKAGE NULLID.SYSSH200 TO GROUP WP_PZN_CONFIG_USERS;
GRANT ALTERIN, CREATEIN, DROPIN ON SCHEMA feedback TO GROUP WP_PZN_CONFIG_USERS;
GRANT USE OF TABLESPACE USERSPACE1 TO GROUP WP_PZN_CONFIG_USERS;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO GROUP WP_PZN_CONFIG_USERS;

CONNECT RESET;

CONNECT TO WPSDB USER db2inst1 USING diet4coke;
CREATE SCHEMA likeminds AUTHORIZATION db2inst1;
COMMIT;

GRANT CONNECT, CREATETAB ON DATABASE TO GROUP WP_PZN_CONFIG_USERS;
GRANT EXECUTE ON PACKAGE NULLID.SYSSH200 TO GROUP WP_PZN_CONFIG_USERS;
GRANT ALTERIN, CREATEIN, DROPIN ON SCHEMA likeminds TO GROUP WP_PZN_CONFIG_USERS;
GRANT USE OF TABLESPACE USERSPACE1 TO GROUP WP_PZN_CONFIG_USERS;
GRANT USAGE ON WORKLOAD SYSDEFAULTUSERWORKLOAD TO GROUP WP_PZN_CONFIG_USERS;

CONNECT RESET;