-- Create login user cwdb01 (can replace with your login user and password)
CREATE USER cwdb01 
	IDENTIFIED BY p0rtal4u 
	DEFAULT TABLESPACE USERS 
	TEMPORARY TABLESPACE TEMP; 


--------------------------------------------------------------
-- SETUP for schema RELEASE
--------------------------------------------------------------
CREATE USER release 
	IDENTIFIED BY p0rtal4u 
	DEFAULT TABLESPACE USERS 
	TEMPORARY TABLESPACE TEMP; 
        
        
GRANT UNLIMITED TABLESPACE TO release;   
        
CREATE ROLE WP_BASE_CONFIG_USERS NOT IDENTIFIED;
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_BASE_CONFIG_USERS;
      
      
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_CONFIG_USERS;
GRANT WP_BASE_CONFIG_USERS TO cwdb01;
    
    
CREATE ROLE WP_BASE_RUNTIME_USERS NOT IDENTIFIED;
GRANT CREATE SESSION TO WP_BASE_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_RUNTIME_USERS;
GRANT WP_BASE_RUNTIME_USERS TO cwdb01;
 
--------------------------------------------------------------
-- SETUP for schema RELEASE
--------------------------------------------------------------
CREATE USER community 
	IDENTIFIED BY p0rtal4u 
	DEFAULT TABLESPACE USERS 
	TEMPORARY TABLESPACE TEMP; 
        
        
GRANT UNLIMITED TABLESPACE TO community;   
        
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_BASE_CONFIG_USERS;
      
      
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_CONFIG_USERS;
GRANT WP_BASE_CONFIG_USERS TO cwdb01;
    
    
GRANT CREATE SESSION TO WP_BASE_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_RUNTIME_USERS;
GRANT WP_BASE_RUNTIME_USERS TO cwdb01;
 
--------------------------------------------------------------
-- SETUP for schema RELEASE
--------------------------------------------------------------
CREATE USER customization 
	IDENTIFIED BY p0rtal4u 
	DEFAULT TABLESPACE USERS 
	TEMPORARY TABLESPACE TEMP; 
        
        
GRANT UNLIMITED TABLESPACE TO customization;   
        
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_BASE_CONFIG_USERS;
      
      
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_CONFIG_USERS;
GRANT WP_BASE_CONFIG_USERS TO cwdb01;
    
    
GRANT CREATE SESSION TO WP_BASE_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_BASE_RUNTIME_USERS;
GRANT WP_BASE_RUNTIME_USERS TO cwdb01;
 
--------------------------------------------------------------
-- SETUP for schema RELEASE
--------------------------------------------------------------
CREATE USER jcr 
	IDENTIFIED BY p0rtal4u 
	DEFAULT TABLESPACE USERS 
	TEMPORARY TABLESPACE TEMP; 
        
        
GRANT UNLIMITED TABLESPACE TO jcr;   
        
CREATE ROLE WP_JCR_CONFIG_USERS NOT IDENTIFIED;
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_JCR_CONFIG_USERS;
      
GRANT CREATE TABLESPACE, DROP TABLESPACE,
	CREATE ANY SEQUENCE, DROP ANY SEQUENCE,
	CREATE ANY TRIGGER, DROP ANY TRIGGER,
	CREATE ANY TYPE, DROP ANY TYPE, EXECUTE ANY TYPE,
	CREATE ANY VIEW, DROP ANY VIEW
	TO WP_JCR_CONFIG_USERS;
        
GRANT SELECT ON DBA_IND_COLUMNS to WP_JCR_CONFIG_USERS;
GRANT SELECT ON DBA_INDEXES to WP_JCR_CONFIG_USERS;
      
      
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_JCR_CONFIG_USERS;
GRANT WP_JCR_CONFIG_USERS TO cwdb01;
    
    
CREATE ROLE WP_JCR_RUNTIME_USERS NOT IDENTIFIED;
GRANT CREATE SESSION TO WP_JCR_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_JCR_RUNTIME_USERS;
GRANT WP_JCR_RUNTIME_USERS TO cwdb01;
 
--------------------------------------------------------------
-- SETUP for schema RELEASE
--------------------------------------------------------------
CREATE USER feedback 
	IDENTIFIED BY p0rtal4u 
	DEFAULT TABLESPACE USERS 
	TEMPORARY TABLESPACE TEMP; 
        
        
GRANT UNLIMITED TABLESPACE TO feedback;   
        
CREATE ROLE WP_PZN_CONFIG_USERS NOT IDENTIFIED;
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_PZN_CONFIG_USERS;
      
      
GRANT CREATE ANY SEQUENCE, DROP ANY SEQUENCE TO WP_PZN_CONFIG_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_PZN_CONFIG_USERS;
GRANT WP_PZN_CONFIG_USERS TO cwdb01;
    
    
CREATE ROLE WP_PZN_RUNTIME_USERS NOT IDENTIFIED;
GRANT CREATE SESSION TO WP_PZN_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_PZN_RUNTIME_USERS;
GRANT WP_PZN_RUNTIME_USERS TO cwdb01;
 
--------------------------------------------------------------
-- SETUP for schema RELEASE
--------------------------------------------------------------
CREATE USER likeminds 
	IDENTIFIED BY p0rtal4u 
	DEFAULT TABLESPACE USERS 
	TEMPORARY TABLESPACE TEMP; 
        
        
GRANT UNLIMITED TABLESPACE TO likeminds;   
        
GRANT ALTER ANY TABLE, CREATE ANY TABLE, DROP ANY TABLE,
	CREATE ANY INDEX, DROP ANY INDEX,
	INSERT ANY TABLE, UPDATE ANY TABLE, SELECT ANY TABLE, DELETE ANY TABLE,
	CREATE SESSION
	TO WP_PZN_CONFIG_USERS;
      
      
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_PZN_CONFIG_USERS;
GRANT WP_PZN_CONFIG_USERS TO cwdb01;
    
    
GRANT CREATE SESSION TO WP_PZN_RUNTIME_USERS;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO WP_PZN_RUNTIME_USERS;
GRANT WP_PZN_RUNTIME_USERS TO cwdb01;

--------------------------------------------------------------
-- TABLESPACE CREATION
--------------------------------------------------------------
-- Create a TABLESPACE, update the path to your database directory
CREATE TABLESPACE ICMLFQ32 DATAFILE 'jdbc:oracle:thin:@//CWDB01.td.clckwrk.com:1521/CWDB01.td.clckwrk.com/WPJCR/data/WPJCR_ICMLFQ32_01.dbf' SIZE 300M REUSE AUTOEXTEND ON NEXT 10M maxSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE;   
CREATE TABLESPACE ICMLNF32 DATAFILE 'jdbc:oracle:thin:@//CWDB01.td.clckwrk.com:1521/CWDB01.td.clckwrk.com/WPJCR/data/WPJCR_ICMLNF32_01.dbf' SIZE 25M REUSE AUTOEXTEND ON NEXT 10M maxSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE;   
CREATE TABLESPACE ICMVFQ04 DATAFILE 'jdbc:oracle:thin:@//CWDB01.td.clckwrk.com:1521/CWDB01.td.clckwrk.com/WPJCR/data/WPJCR_ICMVFQ04_01.dbf' SIZE 25M REUSE AUTOEXTEND ON NEXT 10M maxSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE;   
CREATE TABLESPACE ICMSFQ04 DATAFILE 'jdbc:oracle:thin:@//CWDB01.td.clckwrk.com:1521/CWDB01.td.clckwrk.com/WPJCR/data/WPJCR_ICMSFQ04_01.dbf' SIZE 150M REUSE AUTOEXTEND ON NEXT 10M maxSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE;   
CREATE TABLESPACE ICMLSNDX DATAFILE 'jdbc:oracle:thin:@//CWDB01.td.clckwrk.com:1521/CWDB01.td.clckwrk.com/WPJCR/index/WPJCR_ICMLSNDX_01.dbf' SIZE 10M REUSE AUTOEXTEND ON NEXT 10M maxSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
